export const HOVER_MEN='HOVER_MEN'
export const HOVER_WOMEN='HOVER_WOMEN'
export const HOVER_KID='HOVER_KID'
export const HOVER_BEAUTY='HOVER_BEAUTY'
export const HOVER_PROFILE='HOVER_PROFILE'
export const HOVER_WISHLIST='HOVER_WISHLIST'
export const HOVER_BAG='HOVER_BAG'



export const REQUEST_PRODUCT='REQUEST_PRODUCT'
export const SUCCESS_PRODUCT='SUCCESS_PRODUCT'
export const FAILURE_PRODUCT='FAILURE_PRODUCT'

export const REQUEST_BAG='REQUEST_BAG'
export const SUCCESS_BAG='SUCCESS_BAG'
export const FAILURE_BAG='FAILURE_BAG'


export const REQUEST_WISHLIST='REQUEST_WISHLIST'
export const SUCCESS_WISHLIST='SUCCESS_WISHLIST'
export const FAILURE_WISHLIST='FAILURE_WISHLIST'
